name: stroll
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/svgs/
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: lib/assets/fonts/ProximaNova-Regular.otf
        - asset: lib/assets/fonts/Proxima Nova Black.otf
          weight: 800
        - asset: lib/assets/fonts/Proxima Nova Extrabold.otf
          weight: 700
        - asset: lib/assets/fonts/Proxima Nova Bold.otf
          weight: 600
        - asset: lib/assets/fonts/Proxima Nova Semibold.otf
          weight: 500
        - asset: lib/assets/fonts/Proxima Nova Thin.otf
          weight: 300
